### ISSUE TITLE
How is this meant to be used?

### ISSUE THREAD

**Issue by TinyPaws** [ThatGamerBlue/osrs-prox-chat#1]
Can you give what im needed to do to actually get this plugin working?

**Comment by ThatGamerBlue** [comment]
you need to run your own voice server. to do this:

uncomment line 3 and lines 6-84 in the build.gradle
run the gradle task `buildServer`
copy the server jar file from build/libs/ to its own folder
run `java -jar *-server.jar`  in the new folder to generate the config file
change the password in the config file to one of your choice
re-run the server jar
fill out the server ip, port and password in the plugin
turn the plugin off and on again

**Comment by TinyPaws** [comment]
any hints how to fix?

![image](https://user-images.githubusercontent.com/36816996/116828575-7a961680-ab97-11eb-95ea-b994b0fcafac.png)

**Comment by ThatGamerBlue** [comment]
try redownloading the repo, looks like your build.gradle might be corrupted. i pushed a commit to uncomment the stuff in the gradle file so all you have to do is `gradlew buildServer` and follow from step 3

**Comment by TinyPaws** [comment]
ok we are getting somewhere now its saying no main manifest on the build (that is the only jar file it builds)

![image](https://user-images.githubusercontent.com/36816996/116829743-7e2c9c00-ab9d-11eb-809c-3b5b4305f82d.png)

**Comment by BuzzfeedBlue** [comment]
I just attempted this and it builds, but cant be run due to missing a main manifest attribute

**Comment by TinyPaws** [comment]
> I just attempted this and it builds, but cant be run due to missing a main manifest attribute
> Edit: through an ide I can run the commands to get the server going and connect to it, but if I give my own ip or port it will return an error. So how could another player connect to the ip of 0.0.0.0?

i have been wondering that as well but i have got it to work but not track the location of the current player (so i can have myself talk to myself in a fixed location)

![image](https://user-images.githubusercontent.com/36816996/116832312-84764480-abac-11eb-9f2b-d810beac7d06.png)

**Comment by ThatGamerBlue** [comment]
if the server starts and you connect successfully it should start working, are there any errors in your client.log file? `%userprofile%\.runelite\logs\client.log`

**Comment by BuzzfeedBlue** [comment]
On my end, I am only able to run through an ide, not with a command terminal. And if I change the config to show my public IP it will not bind to it. There were no errors within runelite so I doubt the log would shed light on this, and I'm at work currently so I can't grab the server side errors. Basically it looked like it didn't like my port or up change, and only ran with 0.0.0.0 on 30666

**Comment by ThatGamerBlue** [comment]
are you running the client and server on the same machine?

**Comment by BuzzfeedBlue** [comment]
I was yeah, is it expected to be one machine per

**Comment by ThatGamerBlue** [comment]
it worked when i tried it, i'll see if i can figure out whats going on

**Comment by ThatGamerBlue** [comment]
seems to be working fine for me, here's my settings
![image](https://user-images.githubusercontent.com/29176781/116893377-ce9d0b80-ac28-11eb-9bfa-2be5af57901c.png)
is your microphone marked as the default device in windows?

**Comment by BuzzfeedBlue** [comment]
What is the server address you are using in runelite? Your public ip? I had assumed if I wanted others to be able to connect I would need to change the bindaddress setting in the config file (even though you only had said to change the password)

**Comment by ThatGamerBlue** [comment]
a bind address of 0.0.0.0 means "bind to all available network interfaces" so it binds to 127.0.0.1 and your private internal ip and (usually) your public ip too, assuming your router has port forwarding applied correctly

**Comment by BuzzfeedBlue** [comment]
Im back for lunch and with the same files I used yesterday it seems to be working as you intended moreso? CMD runs everything now and im not sure why it wasnt yesterday. But im getting the same bind issue. I have tried with and without port 30666 forwarded. The config it generated for me also auto applied my public ip, and yesterday it was generated with 0.0.0.0

`Successfully loaded config.
Writing config file...
Successfully written config file
00:03  INFO: [kryonet] Server closed.
Exception in thread "main" java.net.BindException: Cannot assign requested address: bind
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:469)
        at java.base/sun.nio.ch.Net.bind(Net.java:458)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:72)
        at com.esotericsoftware.kryonet.Server.bind(Server.java:134)
        at com.thatgamerblue.osrs.proxchat.server.net.ServerNetworkHandler.connect(ServerNetworkHandler.java:154)
        at com.thatgamerblue.osrs.proxchat.server.ProxChatServer.start(ProxChatServer.java:153)
        at com.thatgamerblue.osrs.proxchat.server.ProxChatServer.main(ProxChatServer.java:70)`

**Comment by TinyPaws** [comment]
hey blue can you add me on discord LegionXY#0188 as im still having problems and it would be faster talking there then on here

**Comment by TinyPaws** [comment]
just a update to build this you need have gradle 6.6.1 to even build the project i worked that out myself :)
